name: CI
on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'CHANGELOG.md'
      - 'renovate.json'
      - '.gitignore'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows, macos, ubuntu ]
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: danysk/action-checkout@0.2.19
      - name: Get branch name
        id: branch
        uses: tj-actions/branch-names@v8
      - uses: DanySK/build-check-deploy-gradle-action@3.5.7
        with:
          deploy-command: |
            ./gradlew signKotlinOSSRHPublication --parallel
            ./gradlew uploadKotlinOSSRHToMavenCentralNexus closeStagingRepositoryOnMavenCentral
          should-run-codecov: ${{ contains('Linux', runner.os) }}
          should-deploy: >-
            ${{
              contains('Linux', runner.os)
              && contains(github.repository, 'DanySK/khttp')
              && contains('push workflow_dispatch', github.event_name)
              && contains('master', steps.branch.outputs.current_branch)
            }}
          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          signing-key: ${{ secrets.SIGNING_KEY }}
          signing-password: ${{ secrets.SIGNING_PASSWORD }}
  Release:
    needs:
      - build
    runs-on: ubuntu-latest
    if: >-
      contains('push workflow_dispatch', github.event_name)
      && contains(github.repository, 'DanySK/khttp')
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - uses: DanySK/build-check-deploy-gradle-action@3.5.7
        with:
          java-version: 17
          build-command: true
          check-command: true
          deploy-command: |
            npm install
            npx semantic-release
          should-run-codecov: false
          should-deploy: true
          should-validate-wrapper: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          signing-key: ${{ secrets.SIGNING_KEY }}
          signing-password: ${{ secrets.SIGNING_PASSWORD }}
